### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

### ISSUE THREAD

**Issue by stantoncbradley** [applivery/applivery-ios-sdk#10]
Getting error:
```
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```
when installing applivery through cocoa pods into react native app. React native app doesn't otherwise use swift.
Adding user defined property `SWIFT_VERSION` and setting it to 3.2 (which is what it is set to in applivery-ios-sdk) leads to same error

**Comment by stantoncbradley** [comment]
deleting xcode workspace & doing a fresh pod install: getting these errors:
![image](https://user-images.githubusercontent.com/5314103/38590308-2fd0099a-3ce5-11e8-8d97-b81f68e61728.png)

**Comment by stantoncbradley** [comment]
ok after nuking the workspace and reinstalling the pods, this is the error i get:
![image](https://user-images.githubusercontent.com/5314103/38593458-4e4f9988-3cf6-11e8-93a6-5321a3773cd3.png)

**Comment by stantoncbradley** [comment]
podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Mixpanel'

target 'lcard_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  pod 'Applivery', '~> 2.5'
  # Pods for lcard_app

  target 'lcard_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lcard_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by CesarTrigo** [comment]
Hi @stantoncbradley 
Thank you for opening the issue and provide the details
Our team is looking into it and we'll come back to you as soon as possible.
Best,
C.

**Comment by stantoncbradley** [comment]
@CesarTrigo thanks. this is blocking our iOS release

**Comment by stantoncbradley** [comment]
removing the pod linked binaries in the test target seems to have fixed this
https://github.com/CocoaPods/CocoaPods/issues/5762#issuecomment-240588740
