### ISSUE TITLE
Force update not working

### ISSUE THREAD

**Issue by ttupper92618** [applivery/applivery-ios-sdk#11]
Added applivery to my appDelegate as indicated below:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        // applivery
        let applivery = Applivery.shared
        applivery.logLevel = .info
        applivery.start(apiKey: "myKey", appId: "myAppId", appStoreRelease: false)
        
        Applivery.shared.textLiterals = TextLiterals(
           < a bunch of literals >
        )
        
        return true
        
    }
```

The app is configured in dashboard with automatic and forced updates enabled, and the SDK for builds is detected.  App versioning is set in bundle version.  When a new build is uploaded to the site, users are not forced to update, and are not notified that a new version is available.

iOS versions:  11.2, 11.3
Devices: iPhone 5S, 6S, X

**Comment by CesarTrigo** [comment]
Hi @ttupper92618 , thank you for contacting.
From a configuration perspective it seems to be ok.
However we need to get access to the Applivery logs of your App (displayed in the console) when launching the App itself. They will clearly show the comparisons between versions and the actions taken by the SDK so please, can you share them with us?

Thank you,

C.

**Comment by ttupper92618** [comment]
So, it seems to me that it is using bundleVersion AND build number... or perhaps just build number.  Here are the logs:

Applivery :: Applivery is starting...
Applivery :: Applivery is listening for screenshot event
Applivery :: Applivery configuration was updated
Applivery :: Checking if app version: 1 is older than minVersion: 0.01
Applivery :: Checking if app version: 1 is older than last build version: 1

Note that it thinks app version is 1.  

I think this may be an expectations gap.  I have been setting the bundle version string (under identity), and it is clear to me now that the SDK is looking at bundle version from the target.

Sorry - think I may simply have faulty assumptions.  You may want to update your docs though in order to be a bit more specific.

**Comment by ttupper92618** [comment]
Ha ha - love it!  Build number from "identity" shows up as "Bundle Version" under "info" in Xcode 9.2.

**Comment by CesarTrigo** [comment]
Hi @ttupper92618, thank you for your comments
As you mentioned, Build number and bundle version are the same in iOS.
We will take your recommendation to be included as part of the documentation so we can avoid future misunderstandings.
Best,
C.
