### ISSUE TITLE
Migrate to Swift 4+

### ISSUE THREAD

**Issue by mszaro** [applivery/applivery-ios-sdk#16]
Applivery SDK cannot be compiled under the forthcoming Xcode 10.2, as support for Swift < 4.0 has been dropped.

The target should be migrated to at least Swift 4.0, but ideally 5.0, as the pod will be unusable once Xcode 10.2 drops.

`SWIFT_VERSION '3.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Applivery')`

**Comment by CesarTrigo** [comment]
Hi @mszaro thank you for reporting the issue.
The team is working on a new version that will be fixing this and other minor issues.
You can expect it to be released by the first week of March.
Thanks,
C.

**Comment by mszaro** [comment]
Gracias amigo! Appreciate the quick update. My team is happy to help you in any way.

-M
