### ISSUE TITLE
Adding Applivery to React Native app with statically bound Cocoa Pods

### ISSUE THREAD

**Issue by driddle** [applivery/applivery-ios-sdk#17]
I am having trouble compiling with the Applivery 3.0 Pod.

In order to generate the compatibility header, I am loading it in the Podfile as follows:

pod 'Applivery', '~> 3.0',
    :modular_headers => true

Unfortunately, when the main app is called, XCode throws an error:

Applivery/Swift Compatibility Header/ Applivery-Swift.h:342:12: parameter 'appToken' not found in the function declaration [-Wdocumentation]

The line in that file is:
///  \param appToken Your developer's Api Key

Which sits above the (void)startWithAPIKey method, which is marked deprecated, and does not accept that property.

Do you have any suggestions or fixes on a way to compile your SDK correctly into my app?

**Comment by CesarTrigo** [comment]
Dear @driddle 
Thank you for contacting us.
Version 3.0 of our SDK has been released as a **pre-release** a few weeks ago, preparing the launching of our brand new dashboard that will be available in June. In the meantime, please downgrade your SDK version to [2.7.2](https://github.com/applivery/applivery-ios-sdk/releases/tag/v2.7.2) and please follow the v2-7.2 docs under: https://github.com/applivery/applivery-ios-sdk/blob/eed82fa4a35df58b119ea6e6c7d8f9b077b032fc/README.md

As stated in the v3.x docs, 3.x version do not have retrocompatibility with the previous version of the dashboard.

Hope this helps you solve the issue.

By the way, if you want to start testing the new version of the platform, please send us an email to support@applivery.com and we'll happy to grant you access.

Have a nice day,
C.
