### ISSUE TITLE
SPM library

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-ios-sdk#25]

**Comment by Alesete** [comment]
Blocked until SPM supports resources (localization, storyboards & xibs). It seems will be released in swift 5.3 (https://forums.swift.org/t/se-0271-package-manager-resources/30730/74)

**Comment by RafaelFernandezAlv** [comment]
Hi, with new swift-tools-version:5.3 you can support resources on the package, included storyboard, xibs and localization. You can check here:
https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package
https://developer.apple.com/documentation/swift_packages/localizing_package_resources

Can you develop the support for SPM?

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv thank you for sharing the information. Actually, the SPM library is already under development.

**Comment by RafaelFernandezAlv** [comment]
Hi @CesarTrigo,

Would you know an estimate of when the development might be finished? We are in the process of migrating from cocoapods to SPM and this is the last library we would need.

Thanks!

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv , we have – finally – released the SPM support for the iOS SDK. It's available in [v3.2.0](https://github.com/applivery/applivery-ios-sdk/releases/tag/v3.2.0).
C.
