### ISSUE TITLE
README references Palette incorrectly 

### ISSUE THREAD

**Issue by maxlapides** [applivery/applivery-ios-sdk#28]
The README says: "The SDK has literals by default so, if you only need to change the update messages, yo can do this:"

And then this code block is provided:

```swift
Applivery.shared.textLiterals = Palette(
    appName: "MyApp",
    otaUpdateMessage: "There is a new version available for download. Do you want to update to the latest version?",
    forceUpdateMessage: "Sorry this App is outdated. Please, update the App to continue using it"
)
```

In this case, `Palette` should be `TextLiterals`

**Comment by CesarTrigo** [comment]
Hi @maxlapides !
Thank you for the feedback. Moving the issue to @Alesete to take a look into it.
C.

**Comment by Alesete** [comment]
Thanks @maxlapides !  we've just fix the error 🙂

**Comment by maxlapides** [comment]
Thank you!
