### ISSUE TITLE
Conflict with localization file

### ISSUE THREAD

**Issue by RafaelFernandezAlv** [applivery/applivery-ios-sdk#34]
Hi, 
We are having a conflict with the Localizable.string file when we do an installation with cocoapods. The name of the file conflicts with the application's own files and causes us to lose the application's own literals.
Can you change the name of the "Localizable.strings" file in the SDK to something specific to Applivery ("LocalizableApplivery.strings" for example) or install these files into a "resource_bundles" as indicated in the cocoapods documentation?

https://guides.cocoapods.org/syntax/podspec.html#resource_bundles

**Comment by CesarTrigo** [comment]
After several tests (and even releasing a new version) we have detected that it's not that easy as changing the resource name and it requires further investigation to make it work under cocoapod's static frameworks handling.

**Comment by Alesete** [comment]
As a workaround you can use the directive `use_frameworks!` in your Podfile to compile it like a dynamic framework (that has no problem with resources). But don't change it yet if is not urgent to you. We are planning to release this week a version to support this, so you can load applivery as a static framework which is the most suitable solution and a nice upgrade for the SDK.

Thanks an sorry for the inconvenience!

**Comment by Alesete** [comment]
Hi @RafaelFernandezAlv ! This is fixed in the recent release [v3.1.3](https://github.com/applivery/applivery-ios-sdk/releases/tag/v3.1.3)

We have test it and now is working fine, but if you see something don't hesitate to contact us!

Thanks a lot for your feedback 👍
