### ISSUE TITLE
Disallowed LLVM instrumentation

### ISSUE THREAD

**Issue by stantoncbradley** [applivery/applivery-ios-sdk#7]
Installing Applivery framework manually, iTunes connect rejects our archive submission with error
```
Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.
```
This happens even after including the build phase script outlined [here](https://github.com/applivery/applivery-ios-sdk#embedded-frameworks-and-appstore-submissions).

I can confirm Applivery is the culprit because I ran the instructions outlined on Apple's [support page](https://developer.apple.com/library/content/qa/qa1964/_index.html) to trace which binaries include LLVM instrumentation, and when I ran listing 3:
```
otool -l -arch all <MY_PATH>/Frameworks/Applivery.framework/Applivery | grep __llvm_prf
```
 on the Applivery framework we manually installed, I got this output:
```
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
```
According to the docs:
```
Starting with Xcode 9, if the Gather coverage data option is enabled on the scheme, regular builds for the Run action will also build with code coverage instrumentation, but archive builds will not. If your app's build uses scripts to generate or move build products into place, you need to ensure these scripts only use archived build products when receiving the archive build action; otherwise, build products created with the build action will contain instrumentation and result in a rejection from the App Store.
```
The Applivery framework needs to be updated to not include LLVM instrumentation, at least for release.
Please help, as this is currently blocking production builds, and either this gets fixed, or we can't use Applivery.

Thanks, let me know if I can provide any additional information.

**Comment by Alesete** [comment]
Thanks for the feedback @stantoncbradley we are investigating this issue.

**Comment by Alesete** [comment]
Hi @stantoncbradley I've just upload a hotfix disabling code coverage: [Hotfix v2.5.1](https://github.com/applivery/applivery-ios-sdk/releases/tag/v2.5.1)

I download it and exec `otool -l -arch all ./Applivery.framework/Applivery | grep __llvm_prf` and nothing  was "echo" in the shell this time.

Hope this works for you!

**Comment by stantoncbradley** [comment]
thanks for the quick turnaround! App finished processing, will let you know if there are anymore issues

**Comment by Alesete** [comment]
I'm very happy to heard that! Thanks very much for your feedback!
