### ISSUE TITLE
Running UI Kit stuff in background thread

### ISSUE THREAD

**Issue by SPopenko** [applivery/applivery-ios-sdk#8]
Guys, this code is running in the background thread. This is wrong, UI code should be executed on main thread only.

```
	fileprivate func rootIsReady() -> Bool {
		let app = UIApplication.shared
		let window = **app.keyWindow**
		guard let rootVC = window?.rootViewController else { return false }

		return rootVC.isViewLoaded
	}
```

**Comment by Alesete** [comment]
Hello @SPopenko, thanks for your feedback!

We were aware of that (xcode has been warning us like crazy!), and it was just fixed yesterday in develop (commit 6fcdd5b)

This fix will be included in next release v2.6 (probably today)

**Comment by SPopenko** [comment]
@Alesete great! thank you!

**Comment by SPopenko** [comment]
@Alesete I've reviewed that changes and unfortunately we need this ticket to be reopened. 
No we have 2 issues with this pice of code:
```
	private func rootIsReady() -> Bool {
		let app = UIApplication.shared
		var window: UIWindow?
		var rootVC: UIViewController?
		runOnMainThread { <-------------------------This couse data race condition. runOnMainThread is async it means you could simultaniusly access rootVC from 2 threads.  
			window = app.keyWindow
			rootVC = window?.rootViewController
		}
		Thread.sleep(forTimeInterval: 0.1)
		guard let unwrappedRootVC = rootVC else { return false }
		return unwrappedRootVC.isViewLoaded <---------------------- This is usage of UIKit in background. 
	}
```

Here is offered solution:
```
	private func rootIsReady() -> Bool {
        var isReady = false
        // Wait until main thread complete check
		DispatchQueue.main.sync {
            isReady = UIApplication
                .shared.keyWindow?
                .rootViewController?
                .isViewLoaded ?? false
		}
        return isReady
	}
```

It's workable and follows the existing design pattern but I would recommend using Dispatch groups for strategy in general. But that is another story. 
Also enabling **thread sanitizer**  could help a lot!

**Comment by CesarTrigo** [comment]
Hi @SPopenko , thank you for the contribution.
I have reopened the issue to “Under investigation” and we’ll come back to you ASAP.
Best,
C.
