### ISSUE TITLE
cannot run in release mode locally

### ISSUE THREAD

**Issue by stantoncbradley** [applivery/applivery-ios-sdk#9]
Using manually imported framework Hotfix v2.5.1 (https://github.com/applivery/applivery-ios-sdk/issues/7)

we are unable to run the ios app locally in the release scheme:
```
dyld: Library not loaded: @rpath/Applivery.framework/Applivery
  Referenced from: /Users/cole.bradley/Library/Developer/CoreSimulator/Devices/FBD58850-8F6B-4FDD-9DDB-1E569CF12DBD/data/Containers/Bundle/Application/81251C20-9978-4689-B186-3D66A3D99419/lcard_app.app/lcard_app
  Reason: no suitable image found.  Did find:
	/Users/cole.bradley/Library/Developer/CoreSimulator/Devices/FBD58850-8F6B-4FDD-9DDB-1E569CF12DBD/data/Containers/Bundle/Application/81251C20-9978-4689-B186-3D66A3D99419/lcard_app.app/Frameworks/Applivery.framework/Applivery: no matching architecture in universal wrapper
(lldb) 
```
please help! thanks

**Comment by stantoncbradley** [comment]
this is really annoying. @Alesete has anyone had a chance to look into this?

**Comment by Alesete** [comment]
Hi @stantoncbradley and sorry! I wasn't available last week.

I can't reproduce the error, but it usually shows up when the framework is not properly imported into Xcode project. Have you added the framework to the "Embedded Binaries" section?

**Comment by stantoncbradley** [comment]
Yes we added Applivery to the Embedded Binaries section. Everything builds fine and we are able to leverage Applivery in our staging scheme, and release the app into production. Just the app crashes when running on the simulator locally with release scheme.  I can run it on my device locally with release scheme. Maybe it's related to the hotfix for v2.5.1? I think there's no suitable image for the simulator?

**Comment by stantoncbradley** [comment]
works thanks!!!

**Comment by CesarTrigo** [comment]
Thanks for confirming @stantoncbradley!
